wolverine/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  resources :applications do
    collection do
      post 'edit_applic'
      post 'edit_app'
      post 'complete'
      post 'update_app'
      post 'import'
      get 'upload'
      post 'copy_app'
      get 'copy/:id', to: 'applications#copy'
      match 'new' => 'applications#new', via: [:get, :post], as: :new
      match 'search' => 'applications#search', via: [:get, :post], as: :search
    end
  end

  get 'home/index'

  get 'home/show'

  root to: "home#index"

end

wolverine/app/models/application.rb
class Application < ActiveRecord::Base
  has_many :contents
  has_many :content_details
end

wolverine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

wolverine/app/controllers/applications_controller.rb
require 'csv'
class ApplicationsController < ApplicationController

  @@application_types = {
    '1' => '',
  }

  @@app_types = {
    '1' => '月額固定',
    '2' => '完全成功報酬型',
    '3' => '月額固定＋成功報酬型',
    '4' => '成功報酬フィー',
    '5' => 'ハイクラス・エグゼクティブのみ成功報酬'
  }

  @@staff_names = StaffName.all()
  @@content_names = ContentName.all()

  @@listed = {
    '1' => '未上場',
    '2' => '東証1部',
    '3' => '東証2部',
    '4' => '新興市場',
    '5' => 'その他上場'
  }

  @@app_categories = {
    '1' => '会社',
    '2' => '復活',
    '3' => '商品'
  }

  @@app_sub_categories = {
    '1' => '前金',
    '2' => '後金'
  } 

  @@number_of_member = {
    '1' => '1～10名',
    '2' => '11～30名',
    '3' => '31～100名',
    '4' => '101～300名',
    '5' => '301～1000名',
    '6' => '1001～3000名',
    '7' => '3001～10000名',
    '8' => '10001名以上'
  }

  @@contracts = {
    '1' => '入社日が【納品日】',
    '2' => '入社日の1ヶ月後が【納品日】'
  }

  def index
    @q = Application.search(params[:q])
    @applications = @q.result(distinct: true)
    @app_types = @@app_types
    @staff_names = @@staff_names
  end

  def show
    @application = Application.joins(:contents).find_by(id: params[:id])
    respond_to do |format|
      format.html
      format.xlsx
      format.pdf do
        pdf = render_to_string pdf: "#{params[:id]}.pdf",
        template: "applications/show.pdf.erb",
        encoding: "UTF-8",
        orientation: 'Landscape',
        layout: "pdf.html"
        send_data(pdf)
      end

      format.csv do
        send_data render_to_string, filename: "#{params[:id]}.csv", type: :csv
      end
    end
  end

  def search
    @q = Application.search(params[:q])
    @applications = @q.result(distinct: true).page(params[:page]).per(4).includes(:contents)
    @app_types = @@app_types
    @staff_names = @@staff_names
    @staff_hash = {}
    @staff_names.each do |staff|
      @staff_hash[staff.staff_code] = staff.staff_name
    end
  end

  def new
    @app_types = @@application_types
    @staff_names = @@staff_names
  end

  def edit
    @params = params
    @app = Application.joins(:contents).find_by(id: params[:id])
    @app_types = @@application_types
    @staff_names = @@staff_names
  end

  def edit_applic
    @params = params
    set_list
  end

  def edit_app
    @params = params
    @app = Application.joins(:contents).find_by(id: params[:q][:id])
    set_list
    render "edit_applic"
  end

  def complete
    @params = params
    @application = Application.new(save_applic_params(@params))
    @application.save

    save_contents(@params, @application.id) if params[:contents]
    @params[:q][:draft] == "0" ? render "preview" : render "save_draft"
  end

  def copy
    @params = params
    @app = Application.joins(:contents).find_by(id: params[:id])
    @app_types = @@application_types
    @staff_names = @@staff_names
    render "edit"
  end

  def copy_app
    @params = params
    @app = Application.joins(:contents).find_by(id: params[:q][:id])
    set_list
    render "edit_applic"
  end

  def upload
  end

  def update_app	
    @params = params
    @application = Application.find(params[:q][:id])
    @application.update(save_applic_params(@params))

    update_contents(@params, @application.id) if params[:contents]
    @params[:q][:draft] == "0" ? render "preview" : render "save_draft"

  end

  def import
    @rows = []
    open(params[:csv_file].path, 'r:utf-8') do |f|
      csv = CSV.new(f, encoding: 'utf-8', :headers => :first_row)
      csv.each do |row|
        @rows = row.fields
      end
    end
  end

  private
    def save_applic_params(p)
      @two_keys = ['company_postal_code', 'billing_postal_code']
      @two_keys.each do |key|
        p[:q][key] = p[:q][key + '1'] + "-" + p[:q][key + '2'] if p[:q][key + '1'] && p[:q][key + '2']
        p[:q][key] = "" if p[:q][key] == "-"
        
        p.delete(key + "1")
        p.delete(key + "2")
      end

      @three_keys = ['phone', 'fax', 'billing_phone', 'billing_fax']
      @three_keys.each do |key|
        p[:q][key] = p[:q][key + '1'] + "-" + p[:q][key + '2'] + "-" + p[:q][key + '3'] if p[:q][key + '1'] && p[:q][key + '2'] && p[:q][key + '3']
        p[:q][key] = "" if p[:q][key] == "--"
        
        p.delete(key + "1")
        p.delete(key + "2")
        p.delete(key + "3")
      end

      p.require(:q).permit(:draft, :inhouse, :application_type, :applic_category, :applic_sub_category , :cid, :account_limit, 
        :company_name, :company_name_kana, :company_postal_code , :company_address, :company_address_kana, :phone, :fax, 
        :supervisor, :supervisor_title, :supervisor_kana, :staff, :staff_title, :staff_kana, :number_of_member, :listed, 
        :rule_deadline, :rule_payment_month, :rule_payment_day, :settling_month , :fee_rates1, :fee_rates2, :fee_rates3, 
        :minimum_fee, :repayment_rule_within, :repayment_rule_within_percentage, :repayment_rule_from , :repayment_rule_to, 
        :repayment_rule_percentage, :billing_name, :billing_name_kana, :billing_postal_code , :billing_address, :billing_address_kana, 
        :billing_phone, :billing_fax, :billing_supervisor, :billing_supervisor_title , :billing_supervisor_kana, :billing_staff, 
        :billing_staff_title , :billing_staff_kana, :billing_rule_deadline, :billing_rule_payment_month, :billing_rule_payment_day, 
        :sales_name, :location_name, :update_date)
    end

    def save_contents(p, appid)
      set_content_params(p, appid)

      save_content_params(p).each do |cp|
        content = Content.new(cp)
        content.save
      end
    end

    def update_contents(p, appid)
      set_content_params(p, appid)

      @contents = Content.where("application_id = ?", appid)
      @contents.each do |content|
        update_content_params(p).each do |cp|
          content.update(cp)
        end
      end
    end

    def set_content_params(p, appid)
      p[:contents].each do |cp|
        cp[:application_id] = appid
        cp[:application_type] = p[:q][:application_type]

        @keys = ['delivery_date', 'billing_date', 'payment_date', 'join_date', 'publish_from_date', 'publish_to_date', 'contract_billing_date', 'contract_payment_date']

        @keys.each do |key|
          if cp[key + '_year'] && cp[key + '_month'] && cp[key + '_day']
            cp[key] = cp[key + '_year'] + "-" + cp[key + '_month'] + "-" + cp[key + '_day']
          end
        end
      end
    end

    def save_content_params(p)
      p.require(:contents).map do |p|
        content_params(ActionController::Parameters.new(p.to_hash))
      end
    end

    def update_content_params(p)
      p.require(:contents).map do |p|
        content_params(ActionController::Parameters.new(p.to_hash))
      end
    end

    def content_params(action_param)
      action_param.permit(:id, :application_id, :application_type, :content_type, :note, :delivery_date, :amount, 
      :billing_date, :payment_date, :update_date, :publish_from_date, :publish_to_date, :number_of_offer, :scout_mail_monthly, :scout_mail_left,
      :recommends_monthly, :recommends_left, :job_info_csv, :high_class, :exective, :completion_rate, :number_done_in_3m, :account_number,
      :fee, :join_date, :contract, :contract_billing_date, :contract_payment_date)
    end

    def set_list
      @app_types = @@application_types
      @staff_names = @@staff_names
      @content_names = @@content_names
      @listed = @@listed
      @app_categories = @@app_categories
      @app_sub_categories = @@app_sub_categories
      @number_of_member = @@number_of_member
      @contracts = @@contracts
    end
end

wolverine/app/helpers/application_helper.rb
module ApplicationHelper
end

wolverine/app/helpers/applications_helper.rb
module ApplicationsHelper
end

wolverine/app/views/applications/edit.html.erb
<title>基本情報の登録 | Wolverine</title>
<div id="wrap" class="wrap-form">
  <div class="container">
    <h2 class="headline"><i class="icon-basic-sheet-pen"></i>申込書の作成</h2>
    <% @action = @params[:action] == 'copy' ? 'copy_app' : 'edit_app' %>
    <%= form_tag('/applications/' + @action, method: :post) do %>
      <h3><span class="num">1</span>基本情報の登録</h3>
      <table class="block-default">
        <tr>
          <th>申込書の種類<span class="rq">必須</span></th>
          <td>
            <select name="q[application_type]" id="entry-category" class="wid-m s-required">
              <option value="0">－</option>
            <% @app_types.each do |key, value| %>
              <% @selected = key == @app.application_type ? 'selected' : '' %>
              <option value=<%= key %> <%= @selected %>><%= value %></option>
            <% end %>
            </select>
          </td>
        </tr>
        <tr>
          <th>営業名<span class="rq">必須</span></th>
          <td>
            <select name="q[sales_name]" class="wid-m s-required">
              <option value="0">－</option>
            <% @staff_names.each do |staff| %>
              <% @selected = staff.staff_code == @app.sales_name ? 'selected' : '' %>
              <option value=<%=staff.staff_code%> <%= @selected %>><%=staff.staff_name%></option>
            <% end %>
            </select>
          </td>
        </tr>
        <tr>
          <th>処理方法</th>
          <% @checked = @app.inhouse == 1 ? 'checked' : '' %>
          <td><input type="checkbox" name="q[inhouse]" value="1" id="check01" <%= @checked %>><label for="check01">社内処理のみ</label></td>
        </tr>
      </table><!-- / .block-default -->
      <div class="block-btn">
        <button id="submit-create" type="submit" class="btn-blue btn-l">次へ</button>
      </div><!-- / .block-btn -->
      <input type="hidden" name="q[id]" value=<%= @app.id %>>
    <% end %>
  </div><!-- / .container -->
  <p class="link"><a href="/" class="link-top">← TOPへ戻る</a></p>
</div><!-- / #wrap -->

wolverine/app/views/applications/import.html.erb
<%= @rows %>

wolverine/app/views/applications/index.html.erb
<title>TOP | Wolverine</title>

<div id="wrap" class="wrap-index">
  <div class="container">
    <section class="block-link">
      <h2><a href="./applications/new">新規作成</a></h2>
      <p>申込書の新規作成はこちら</p>
      <i class="icon-basic-sheet-pen"></i>
    </section>
    <section class="block-link">
      <h2><a href="./applications/upload">過去データから作成</a></h2>
      <p>過去の申込書をアップロードして作成する場合はこちら</p>
      <i class="icon-basic-todo-txt"></i>
    </section>
    <section>
      <h2>申込書の検索</h2>
      <%= search_form_for @q, url: search_applications_path, html: { method: :post }, id: 'wrap-search' do |f| %>
        <table class="block-search">
          <tr>
            <th>CID</th>
            <td><%= f.text_field :cid_cont, class: 'is-num', placeholder: '半角数字' %></td>
            <th>クライアント名</th>
            <td><%= f.text_field :company_name_cont %></td>
            <th>対応状況</th>
            <td>
              <%= f.check_box :draft_true, include_hidden: false %><%= f.label :draft_true, '一時保存中のみ' %>
            </td>
          </tr>
          <tr>
            <th>サイト名</th>
            <td>
              <select name="q[applic_category_eq]">
                <option value="">－</option>
                <option value="1">ミドルの転職</option>
                <option value="2">エン転職DB</option>
              </select>
            </td>
            <th>申込書タイプ</th>
            <td>
              <select name="q[application_type_eq]">
                <option value="">－</option>
              <% @app_types.each do |key, value| %>
                <option value="<%= key %>"><%= value%></option>
              <% end %>
              </select>
            </td>
            <th>営業名</th>
            <td>
              <select name="q[sales_name_eq]">
                <option value="">－</option>
                <% @staff_names.each do |staff| %>
                  <option value=<%= staff.staff_code %>><%= staff.staff_name %></option>
                <% end %>
              </select>
            </td>
          </tr>

          <tr>
            <th>納品日</th>
            <td colspan="5" class="date">

              <select id="q_contents_delivery_date_gteq_1i" name="q[contents_delivery_date_gteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_contents_delivery_date_gteq_2i" name="q[contents_delivery_date_gteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_contents_delivery_date_gteq_3i" name="q[contents_delivery_date_gteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日<span class="bar">～</span>
              <select id="q_contents_delivery_date_lteq_1i" name="q[contents_delivery_date_lteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_contents_delivery_date_lteq_2i" name="q[contents_delivery_date_lteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_contents_delivery_date_lteq_3i" name="q[contents_delivery_date_lteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日
            </td>
          </tr>

          <tr>
            <th>登録日</th>
            <td colspan="5" class="date">
              <select id="q_created_at_gteq_1i" name="q[created_at_gteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_created_at_gteq_2i" name="q[created_at_gteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_created_at_gteq_3i" name="q[created_at_gteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日<span class="bar">～</span>
              <select id="q_created_at_lteq_1i" name="q[created_at_lteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_created_at_lteq_2i" name="q[created_at_lteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_created_at_lteq_3i" name="q[created_at_lteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日
            </td>
          </tr>
        </table><!-- / .block-search -->
        <button type="submit" name="commit" id="btn-smt" class="btn-blue btn-l">検索する</button>
      <% end %>
    </section>
  </div><!-- / .container -->
</div><!-- / #wrap -->

wolverine/app/views/applications/new.html.erb
<title>基本情報の登録 | Wolverine</title>
<div id="wrap" class="wrap-form">
  <div class="container">
    <h2 class="headline"><i class="icon-basic-sheet-pen"></i>申込書の作成</h2>
    <%= form_tag('/applications/edit_applic', method: :post) do %>
      <h3><span class="num">1</span>基本情報の登録</h3>
      <table class="block-default">
        <tr>
          <th>申込書の種類<span class="rq">必須</span></th>
          <td>
            <select name="q[application_type]" id="entry-category" class="wid-m s-required">
              <option value="0">－</option>
            <% @app_types.each do |key, value| %>
              <option value=<%= key %>><%= value %></option>
            <% end %>
            </select>
          </td>
        </tr>
        <tr>
          <th>営業名<span class="rq">必須</span></th>
          <td>
            <select name="q[sales_name]" class="wid-m s-required">
              <option value="0">－</option>
            <% @staff_names.each do |staff| %>
              <option value=<%=staff.staff_code%>><%=staff.staff_name%></option>
            <% end %>
            </select>
          </td>
        </tr>
        <tr>
          <th>処理方法</th>
          <td><input type="checkbox" name="q[inhouse]" value="1" id="check01"><label for="check01">社内処理のみ</label></td>
        </tr>
      </table><!-- / .block-default -->
      <div class="block-btn">
        <button id="submit-create" type="submit" class="btn-blue btn-l">次へ</button>
      </div><!-- / .block-btn -->
    <% end %>
  </div><!-- / .container -->
  <p class="link"><a href="/" class="link-top">← TOPへ戻る</a></p>
</div><!-- / #wrap -->

wolverine/app/views/applications/preview.html.erb
<title>申込書データの入力完了 | Wolverine</title>
<div id="wrap" class="wrap-form">
  <div class="container">
    <h2 class="headline"><i class="icon-ecommerce-receipt"></i>申込書データの入力完了</h2>
    <div class="block-preview">
      <h4>データの入力が完了しました</h4>
      <p>・EXCELもしくはPDFで出力し、申込書をカンパニー宛に送信してください。<br>・お申込書フォルダにスキャンされるまで、事務局画面には登録されません。</p>

      <div id="panel-preview">
        ※ここにプレビューを表示※
      </div><!-- / #panel-preview -->

      <div class="block-preview-btn">
        <div>
          <a href="<%=@application.id %>.xlsx" class="btn-l btn-green">Excelで<span>出力</span></a>
          <a href="<%=@application.id %>.pdf" class="btn-l btn-orange">PDFで<span>出力</span></a>
        </div>
        <div>
          <a href="./new" class="btn-l btn-blue">続けて作成</a>
        </div>
      </div><!-- / .block-preview-btn -->

    </div><!-- / .block-preview -->
  </div><!-- / .container -->
  <p class="link"><a href="./" class="link-top">← TOPへ戻る</a></p>
</div><!-- / #wrap -->

wolverine/app/views/applications/search.html.erb
<title>出力データの検索結果 | Wolverine</title>
<div id="wrap">
  <div class="container">
  <h2 class="headline"><i class="icon-basic-todo-txt"></i>出力データの検索結果</h2>
  <div class="wrap-result">
    <section>
      <%= search_form_for @q, url: search_applications_path, html: { method: :post }, id: 'wrap-search' do |f| %>
        <table class="block-search">
          <tr>
            <th>CID</th>
            <td><%= f.text_field :cid_cont, class: 'is-num', placeholder: '半角数字' %></td>
            <th>クライアント名</th>
            <td><%= f.text_field :company_name_cont %></td>
            <th>対応状況</th>
            <td>
              <%= f.check_box :draft_true, include_hidden: false %><%= f.label :draft_true, '一時保存中のみ' %>
            </td>
          </tr>
          <tr>
            <th>サイト名</th>
            <td>
              <select name="q[applic_category_eq]">
                <option value="">－</option>
                <option value="1">ミドルの転職</option>
                <option value="2">エン転職DB</option>
              </select>
            </td>
            <th>申込書タイプ</th>
            <td>
              <select name="q[application_type_eq]">
                <option value="">－</option>
              <% @app_types.each do |key, value| %>
                <option value="<%= key %>"><%= value %></option>
              <% end %>
              </select>
            </td>
            <th>営業名</th>
            <td>
              <select name="q[sales_name_eq]">
                <option value="">－</option>
                <% @staff_names.each do |staff| %>
                  <option value=<%= staff.staff_code %>><%= staff.staff_name %></option>
                <% end %>
              </select>
            </td>
          </tr>
          <tr>
            <th>納品日</th>
            <td colspan="5" class="date">
              <select id="q_contents_delivery_date_gteq_1i" name="q[contents_delivery_date_gteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_contents_delivery_date_gteq_2i" name="q[contents_delivery_date_gteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_contents_delivery_date_gteq_3i" name="q[contents_delivery_date_gteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日<span class="bar">～</span>
              <select id="q_contents_delivery_date_lteq_1i" name="q[contents_delivery_date_lteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_contents_delivery_date_lteq_2i" name="q[contents_delivery_date_lteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_contents_delivery_date_lteq_3i" name="q[contents_delivery_date_lteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日
            </td>
          </tr>
          <tr>
            <th>登録日</th>
            <td colspan="5" class="date">
              <select id="q_created_at_gteq_1i" name="q[created_at_gteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_created_at_gteq_2i" name="q[created_at_gteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_created_at_gteq_3i" name="q[created_at_gteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日<span class="bar">～</span>
              <select id="q_created_at_lteq_1i" name="q[created_at_lteq(1i)]" class="select-m">
                <option value="">－</option>
              <% for num in 2015..2016 do %>
                <option value=<%= num %>><%= num %></option>
              <% end %>
              </select> 年
              <select id="q_created_at_lteq_2i" name="q[created_at_lteq(2i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..12 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 月
              <select id="q_created_at_lteq_3i" name="q[created_at_lteq(3i)]" class="select-s">
                <option value="">－</option>
              <% for num in 1..31 do %>
                <option value=<%= sprintf("%02d",num) %>><%= num %></option>
              <% end %>
              </select> 日
            </td>
          </tr>
        </table><!-- / .block-search -->
        <button type="submit" name="commit" id="btn-smt" class="btn-blue btn-l">検索する</button>
      <% end %>
    </section>
      <div class="wrap-table-result">
        <table class="table-result">
          <thead>
            <tr>
              <th>CID</th>
              <th>クライアント名</th>
              <th>対応状況</th>
              <th>サイト名</th>
              <th>申込書タイプ</th>
              <th>納品日</th>
              <th>営業名</th>
              <th>登録日</th>
              <th>修正 / 出力</th>
            </tr>
          </thead>
          <tbody>
          <% @applications.each do |applic| %>
            <% applic.contents.each do |content| %>
              <tr>
                <td><%= applic.cid %></td>
                <td><%= applic.company_name %></td>
                <% @draft = applic.draft == 1 ? '<span>一時保存中</span>' : '' %></td>
                <td><%== @draft %></td>
                <td><%= applic.applic_category %></td>
                <td><%= applic.application_type %></td>
                <td><%= content.delivery_date.to_date.strftime("%Y/%m/%d") if content.delivery_date.present? %></td>
                <td><%= @staff_hash[applic.sales_name] %></td>
                <td><%= applic.created_at.to_date.strftime("%Y/%m/%d") if applic.created_at.present? %></td>
                <% @link = applic.draft == 0 ? '<a href="/applications/' + applic.id.to_s + '" class="btn-s btn-green">出力</a>' '<a href="/applications/copy/' + applic.id.to_s + '" class="btn-s btn-blue">コピー</a>' : '<a href="/applications/' + applic.id.to_s + '/edit" class="btn-s btn-orange">編集</a>' %>
                <td><%== @link %></td>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table><!-- / .table-result -->
      </div><!-- / .wrap-table-result -->

      <%= paginate @applications %>

    </div><!-- / .wrap-result -->

  </div><!-- / .container -->
  <p class="link"><a href="index.html" class="link-top">← TOPへ戻る</a></p>
</div><!-- / #wrap -->

wolverine/app/views/applications/upload.html.erb
<title>申込書のアップロード | Wolverine</title>
<div id="wrap" class="wrap-upload">
  <div class="container">
    <h2 class="headline"><i class="icon-basic-upload"></i>申込書のアップロード</h2>
    <%= form_tag(import_applications_path, :method => :post, multipart: true) do %>
      <p>アップロードする申込書を選択してください</p>
      <div>
        <%= file_field_tag :csv_file, class: 'file-required' %>
      </div>
      <button type="submit" class="btn-l btn-blue btn-submit">アップロード</button>
    <% end %>
  </div><!-- / .container -->
  <p class="link"><a href="/" class="link-top">← TOPへ戻る</a></p>
</div><!-- / #wrap -->