wolverine/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }

  resources :applications do
    collection do
      post 'edit_applic'
      post 'edit_app'
      post 'complete'
      post 'update_app'
      post 'import'
      get 'upload'
      post 'copy_app'
      get 'copy/:id', to: 'applications#copy'
      match 'new' => 'applications#new', via: [:get, :post], as: :new
      match 'search' => 'applications#search', via: [:get, :post], as: :search
    end
  end

  get 'home/index'

  get 'home/show'

  root to: "home#index"

end

wolverine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
    <header>
        <nav>
            <% if user_signed_in? %>
                <strong<%#= link_to current_user.email, home_show_path %></strong>
                <%#= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% else %>
                <%#= link_to 'サインアップ', new_user_registration_path %>
                <%#= link_to 'ログイン', new_user_session_path %>
            <% end %>
        </nav>
        <a href="/"><h1>Wolverine</h1></a>

    </header>




    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


<%= yield %>
<footer>
  <p>&copy; 2016 enjapan inc.</p>
</footer>

</body>
</html>

wolverine/app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>
  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  <%= wicked_pdf_javascript_include_tag "pdf" %>
</head>
<body>

<%= yield %>

</body>
</html>